### ISSUE TITLE
Downloading a LIST from SP

### ISSUE THREAD

**Issue by sant3e** [chanon-kr/Shared_Function#2]
Can you please help me with downloading a List from a Sharepoint. I have a Client ID and Client Secret. I tried to follow the tutorial on medium, the authentication part works, but not the viewing/downloading the list itself. I am confused about what part of the code are necessary and which aren't
As i understand there is a way to dl as a csv. This would be fine but ... i do have an issue with this: if i try to manually dl the List as a CSV i loose all the special characters (i have some foreign addresses that use special characters that convert into @ or other stuff). This does not happen if a dl as an xlsx. 
Can you please help me?

**Comment by chanon-kr** [comment]
Hello, I assume that...

1. "The list" is a sharepoint list

2. Viewing/downloading, if you follow from my medium article, the method you use is the "download" method.

Please correct me if I was wrong.

In case of list, there's a method in the lazy_SP365 class call "read_list"

`
sp = lazy_SP365(...Your config...) 
`
`
df = sp.read_list("Your Sharepoint List's Name",as_dataframe = True)
`

But this method will read "the real column's name" and it will "also read hidden columns".
So, I suggest creating a new list to test first.

You can also read the full sample of this class [HERE](https://github.com/chanon-kr/Shared_Function/blob/main/samples/sharepoint.ipynb)

**Comment by sant3e** [comment]
Yes the list is a sharepoint list. For now i’m struggling to access the list itself (so i’m not worried...for now... about the real column’s name)

My code for now is this:

 

# Import library
from py_topping.data_connection.sharepoint import lazy_SP365
import pandas as pd

# Create connection
sp = lazy_SP365(site_url='https://mycompany.sharepoint.com/sites/sa/Resources/sfs/'
                   , client_id='xxx'
                   , client_secret='xxx')

 

sp.read_list('MyList_name’, local_location = 'C:/Users/me/Pyproj/Python ETL/')

# pd.read_csv('MyList.csv’)

 

I suspect i’m doing several things wrong *maybe the site url is too much or not enough of the path; same for both arguments in the sp.read_list function

I get the follwoing output now:

 

"C:\Users\me\Pyproj\Python ETL\pyETL\Scripts\python.exe" "C:/Users/me/Pyproj/Python ETL/pyETL.py"

Authen OK

No data found

 

Process finished with exit code 0

 

And if i uncomment the pd.read_csv, i get:

 

Authen OK

No data found

Traceback (most recent call last):

  File "C:\Users\me\Pyproj\Python ETL\pyETL.py", line 18, in <module>

    pd.read_csv('myList.csv')

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper

    return func(*args, **kwargs)

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\io\parsers\readers.py", line 680, in read_csv

    return _read(filepath_or_buffer, kwds)

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\io\parsers\readers.py", line 575, in _read

    parser = TextFileReader(filepath_or_buffer, **kwds)

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\io\parsers\readers.py", line 933, in __init__

    self._engine = self._make_engine(f, self.engine)

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\io\parsers\readers.py", line 1217, in _make_engine

    self.handles = get_handle(  # type: ignore[call-overload]

  File "C:\Users\me\Pyproj\Python ETL\pyETL\lib\site-packages\pandas\io\common.py", line 789, in get_handle

    handle = open(

FileNotFoundError: [Errno 2] No such file or directory: 'SFS Tool T1.csv'

 

Process finished with exit code 1

**Comment by chanon-kr** [comment]
**I accidently click comment before,

Ah, I tried to reproduce your error. I tried wrong url and tried url sharepoint list's name.
And both results are "error : Not found for url or not exist at site..."

I think it is because of the line 91 in this [CLASS](https://github.com/chanon-kr/Shared_Function/blob/main/py_topping/data_connection/sharepoint.py)
That the class do nothing when there is no row to read.

So, one more question, does your list have any rows?
If not, try to add at least 1 row and try again.

**Comment by sant3e** [comment]
Yes, the list has stuff in it (quite a lot). Many columns and rows and Views. 
For now i’m concerned that this is 3rd module i’ve been testing ... they all seem to authenticate just fine (i needed a solution with Client ID&Secret), one of them manages to „see” all Lists ... but none manage to get the items from (any) list.
If i cross this bridge then i will be concerned with the actual view (as it does have certain columns, which most are re-labeled)

**Comment by chanon-kr** [comment]
Can you tell me what kind of list you using? For example, type of columns and dummy data of 2 - 3 rows.

So, I can try to re-create a list and try to read from my side.


By the way, this is how I use to read my list

**My List URL :** https://my_com.sharepoint.com/sites/my_site_name/Lists/my_list_name/AllItems.aspx

then

`
sp = lazy_SP365(site_url='https://my_com.sharepoint.com/sites/my_site_name'
                   , client_id='xxx'
                   , client_secret='xxx')
`

and 

`
df = sp.read_list('my_list_name', as_dataframe = True)
`

if need csv

`
df.to_csv('my_file_name.csv', index = False)
`

**Comment by sant3e** [comment]
I have like 30+ columns, all data types (text, numbers, links, dates). Here is a sample
![List](https://user-images.githubusercontent.com/89382386/173762602-daabf5c0-e4b9-4e55-9c79-019f15a5bcf9.png)

I  changed to 
```
df = sp.read_list("my List_name", as_dataframe=True)
```
I'm getting:
Authen OK
No data found

Process finished with exit code 0

For  site_url i tried up to name of site but then tried all combos after, like:
https://my_com.sharepoint.com/sites/my_site_name
https://my_com.sharepoint.com/sites/my_site_name/Lists/
https://my_com.sharepoint.com/sites/my_site_name/Lists/my_list_name
https://my_com.sharepoint.com/sites/my_site_name/Lists/my_list_name/AllItems.aspx
I even tried with Default.aspx (as this is what i need)
If you are willing i can show you (share screen or something)

**Comment by chanon-kr** [comment]
Sorry for late reply, I travel a lot this week.

I try to duplicate your list, what is the "General T2" column type?

Have you tried creating new list with just a couple of columns & rows, and then try to read from that new list?

**Comment by sant3e** [comment]
Those are links towards another list.
I did, on the sharepoint there are lots of lists, some are easy and small sized, few entries (text and/or numbers)... all return none.
There is something very strange, your library is not the only one giving me this trouble. I really don't understand why a) the list gives me error when i try to download b) the list gives me errors trying to "view" the items (capturing them in a dataframe, or even a simple print)

**Comment by chanon-kr** [comment]
Ummm, do you have other organization or your personal sharepoint for testing?

If other libraries also have the same result, it possible that your organization may close something that effect the list reading.

**Comment by sant3e** [comment]
I need this to work for my organization's lists. It happens the same with all of them. It's an open issue for me ... so if you want to look into it ... anytime. Thank you

**Comment by chanon-kr** [comment]
Ah, I mean if you have other organization or personal sharepoint, you can try to prove your code with them first, just to isolate the problem.

And if your code work well with other sharepoint, it is mean that there are some problems or locks with your organization's sharepoint, which you could inform your sharepoint administrator or Microsoft support to unlock or config those for you.


By the way, if you'd like to share your screen to me, I think this conversation is not safe for you.
I guess, you should contact me by others like email or LinkedIn message.

**Comment by sant3e** [comment]
Yes, it does (quite a lot). Many columns and rows and Views. 

For now i’m concerned this is 3rd module i’ve been testing ... they all seem to authenticate fine (i needed a solution with Client ID&Secret), one of them manages to „see” all Lists ... but non manage to get the items from (any) list.

If i cross this bridge then i will be concerned with the actual view (as it does have certain columns, which most are re-labeled)
